name: JavaScript/TypeScript
concurrency:
  group: js-${{ github.head_ref || 'main' }}
  cancel-in-progress: true
on: ["pull_request"]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install modules
        run: npm install
      - name: Run eslint
        run: npm run lint
      - name: Check Typescript
        run: npm run tscheck
